version: '{branch}-{build}'
build: "off"
image: Visual Studio 2015
cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - pip install pipenv
  - pipenv --python 3
  - pipenv install
  - pipenv install -e .
  - pipenv install -e tests/gbtestapp
  - pipenv install pytest

test_script:
  - pipenv run pytest
